### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by luigiquiros** [sahandha/eif#25]
Hello, i'm trying to install this package, and i'm having error messages and i don't get to install it. Can you help? 

Windows 10 

(base) C:\Users\quirosgu>pip install eif
Collecting eif
  Using cached eif-2.0.2.tar.gz (1.6 MB)
Requirement already satisfied: numpy in c:\users\quirosgu\anaconda3\lib\site-packages (from eif) (1.18.5)
Requirement already satisfied: cython in c:\users\quirosgu\anaconda3\lib\site-packages (from eif) (0.29.21)
Building wheels for collected packages: eif
  Building wheel for eif (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\quirosgu\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\quirosgu\\AppData\\Local\\Temp\\pip-install-wz5r6gph\\eif\\setup.py'"'"'; __file__='"'"'C:\\Users\\quirosgu\\AppData\\Local\\Temp\\pip-install-wz5r6gph\\eif\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\quirosgu\AppData\Local\Temp\pip-wheel-6t9epked'
       cwd: C:\Users\quirosgu\AppData\Local\Temp\pip-install-wz5r6gph\eif\
  Complete output (19 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.8
  copying eif_old.py -> build\lib.win32-3.8
  copying version.py -> build\lib.win32-3.8
  running egg_info
  writing eif.egg-info\PKG-INFO
  writing dependency_links to eif.egg-info\dependency_links.txt
  writing requirements to eif.egg-info\requires.txt
  writing top-level names to eif.egg-info\top_level.txt
  reading manifest file 'eif.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'eif.egg-info\SOURCES.txt'
  running build_ext
  cythoning _eif.pyx to _eif.cpp
  building 'eif' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for eif
  Running setup.py clean for eif
Failed to build eif
Installing collected packages: eif
    Running setup.py install for eif ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\quirosgu\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\quirosgu\\AppData\\Local\\Temp\\pip-install-wz5r6gph\\eif\\setup.py'"'"'; __file__='"'"'C:\\Users\\quirosgu\\AppData\\Local\\Temp\\pip-install-wz5r6gph\\eif\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\quirosgu\AppData\Local\Temp\pip-record-fjpa9g_k\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\quirosgu\Anaconda3\Include\eif'
         cwd: C:\Users\quirosgu\AppData\Local\Temp\pip-install-wz5r6gph\eif\
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    copying eif_old.py -> build\lib.win32-3.8
    copying version.py -> build\lib.win32-3.8
    running egg_info
    writing eif.egg-info\PKG-INFO
    writing dependency_links to eif.egg-info\dependency_links.txt
    writing requirements to eif.egg-info\requires.txt
    writing top-level names to eif.egg-info\top_level.txt
    reading manifest file 'eif.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'eif.egg-info\SOURCES.txt'
    running build_ext
    skipping '_eif.cpp' Cython extension (up-to-date)
    building 'eif' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\quirosgu\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\quirosgu\\AppData\\Local\\Temp\\pip-install-wz5r6gph\\eif\\setup.py'"'"'; __file__='"'"'C:\\Users\\quirosgu\\AppData\\Local\\Temp\\pip-install-wz5r6gph\\eif\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\quirosgu\AppData\Local\Temp\pip-record-fjpa9g_k\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\quirosgu\Anaconda3\Include\eif' Check the logs for full command output.

In this case, i already installed all the dependencies required MVC++, etc, but the problem continues. 

I tried to reproduce it in another WIndows machine and it does not work, contrary, in a Linux based system it does work.

**Comment by zouaghiyassine** [comment]
Did you try the soution in here?
https://github.com/sahandha/eif/issues/14#issuecomment-583010253

A couple of days ago I had problems installing eif and this solution worked perfectly (I am also on windows 10)

**Comment by luigiquiros** [comment]
It works perfectly! thanks you so much!

**Comment by mgckind** [comment]
Thanks @zouaghiyassine !
